[package]
name = "prost_ne_prost"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13"
# Only necessary if using Protobuf well-known types:
prost-types = "0.13"

[build-dependencies]
prost-build = "0.13.5"
