[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13"
prost-types = "0.13"
postgres = { version = "0.19", features = ["with-chrono-0_4"] }
chrono = "0.4.40"


[build-dependencies]
prost-build = "0.13.5"
