[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
image = "0.25.6"
opencv = "0.94.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
